version: "3.8"

services:
  frontend:
    container_name: llm-ragflow-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: llm-ragflow-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - QDRANT_DB_URL=http://llm-ragflow-qdrant:6333
      - CELERY_BROKER_URL=redis://llm-ragflow-redis:6379/0
      - CELERY_BACKEND_URL=redis://llm-ragflow-redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - qdrant
    command: >
      sh -c "celery -A src worker --loglevel=info & 
             CELERY_BROKER_URL=redis://llm-ragflow-redis:6379/0 CELERY_BACKEND_URL=redis://llm-ragflow-redis:6379/0 celery -A src flower --loglevel=info & 
             CELERY_BROKER_URL=redis://llm-ragflow-redis:6379/0 CELERY_BACKEND_URL=redis://llm-ragflow-redis:6379/0 python app.py --host 0.0.0.0 --port 8000"

  redis:
    container_name: llm-ragflow-redis
    image: redis:alpine
    ports:
      - "6381:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: llm-ragflow-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
